apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx-label
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx
#      second container could be may be for backend
    - name: busybox
      image: busybox
  restartPolicy: Never
